name: Deploy Bicep Template

on:
  push:
    branches:
      - main
      - dev
  workflow_dispatch: 

env:
  TEMPLATE-FILE: main.bicep
  DEV_RESOURCE_GROUP: dev-rg
  PROD_RESOURCE_GROUP: prod-rg

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run Bicep linter
      run: az bicep build --file ${{env.TEMPLATE-FILE}}
      
  validate:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: '{"clientId":"${{ secrets.CLIENT_ID }}","clientSecret":"${{ secrets.CLIENT_SECRET }}","subscriptionId":"${{ secrets.SUBSCRIPTION_ID }}","tenantId":"${{ secrets.TENANT_ID }}"}'
      
      - name: Run preflight validation 
        uses: Azure/arm-deploy@v1.0.9
        with:
          template: ${{ env.TEMPLATE-FILE }}
          parameters: main-dev.parameters.json adminPassword=${{ secrets.ADMIN_PASSWORD }} adminUsername=${{ secrets.ADMIN_USERNAME }}
          resourceGroupName: ${{ env.DEV_RESOURCE_GROUP }}
          region: uksouth
          deploymentMode: Validate
          
  preview-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: '{"clientId":"${{ secrets.CLIENT_ID }}","clientSecret":"${{ secrets.CLIENT_SECRET }}","subscriptionId":"${{ secrets.SUBSCRIPTION_ID }}","tenantId":"${{ secrets.TENANT_ID }}"}'
      
      - name: Run what-if
        uses: Azure/arm-deploy@v1.0.9
        with:
          template: ${{ env.TEMPLATE-FILE }}
          parameters: main-dev.parameters.json adminPassword=${{ secrets.ADMIN_PASSWORD }} adminUsername=${{ secrets.ADMIN_USERNAME }}
          resourceGroupName: ${{ env.DEV_RESOURCE_GROUP }}
          region: uksouth
          additionalArguments: --what-if
    
  deploy-dev:
    runs-on: ubuntu-latest
    environment:
      name: Dev
    needs: [lint, validate, preview-dev]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: '{"clientId":"${{ secrets.CLIENT_ID }}","clientSecret":"${{ secrets.CLIENT_SECRET }}","subscriptionId":"${{ secrets.SUBSCRIPTION_ID }}","tenantId":"${{ secrets.TENANT_ID }}"}'

      - name: Deploy to Dev
        uses: Azure/arm-deploy@v1.0.9
        with:
          template: ${{ env.TEMPLATE-FILE }}
          parameters: main-dev.parameters.json adminPassword=${{ secrets.ADMIN_PASSWORD }} adminUsername=${{ secrets.ADMIN_USERNAME }}
          resourceGroupName: ${{ env.DEV_RESOURCE_GROUP }}
          region: uksouth
  
  preview-prod:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: deploy-dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: '{"clientId":"${{ secrets.CLIENT_ID }}","clientSecret":"${{ secrets.CLIENT_SECRET }}","subscriptionId":"${{ secrets.SUBSCRIPTION_ID }}","tenantId":"${{ secrets.TENANT_ID }}"}'
      
      - name: Deploy to Prod
        uses: azure/bicep-actions/deploy@v0
        with:
          template: ${{ env.TEMPLATE-FILE }}
          parameters: main-prod.parameters.json adminPassword=${{ secrets.ADMIN_PASSWORD }} adminUsername=${{ secrets.ADMIN_USERNAME }}
          resourceGroupName: ${{ env.PROD_RESOURCE_GROUP }}
          region: uksouth
          additionalArguments: --what-if

  deploy-prod:
    runs-on: ubuntu-latest
    environment:
      name: Prod
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: [lint, validate, deploy-dev, preview-prod]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: '{"clientId":"${{ secrets.CLIENT_ID }}","clientSecret":"${{ secrets.CLIENT_SECRET }}","subscriptionId":"${{ secrets.SUBSCRIPTION_ID }}","tenantId":"${{ secrets.TENANT_ID }}"}'
      
      - name: Deploy to Prod
        uses: azure/bicep-actions/deploy@v0
        with:
          template: ${{ env.TEMPLATE-FILE }}
          parameters: main-prod.parameters.json adminPassword=${{ secrets.ADMIN_PASSWORD }} adminUsername=${{ secrets.ADMIN_USERNAME }}
          resourceGroupName: ${{ env.PROD_RESOURCE_GROUP }}
          region: uksouth
